// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcJ19OHw_ixUBTzf8Q__LleTVJHPQqI-4',
    appId: '1:330753230821:web:1012041a8e190fc9e9d10c',
    messagingSenderId: '330753230821',
    projectId: 'grocery-app-559ee',
    authDomain: 'grocery-app-559ee.firebaseapp.com',
    storageBucket: 'grocery-app-559ee.firebasestorage.app',
    measurementId: 'G-C21KGMPTKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt6UFwsM_3cr7PwidSOblmZkx9_0jq73E',
    appId: '1:330753230821:android:30c7643af76a3025e9d10c',
    messagingSenderId: '330753230821',
    projectId: 'grocery-app-559ee',
    storageBucket: 'grocery-app-559ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtx8TdATWds_UAr3BhMkL5Mxe2dB5NrLs',
    appId: '1:330753230821:ios:a765ee47c749dfa8e9d10c',
    messagingSenderId: '330753230821',
    projectId: 'grocery-app-559ee',
    storageBucket: 'grocery-app-559ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtx8TdATWds_UAr3BhMkL5Mxe2dB5NrLs',
    appId: '1:330753230821:ios:a765ee47c749dfa8e9d10c',
    messagingSenderId: '330753230821',
    projectId: 'grocery-app-559ee',
    storageBucket: 'grocery-app-559ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcJ19OHw_ixUBTzf8Q__LleTVJHPQqI-4',
    appId: '1:330753230821:web:1bf788134f355931e9d10c',
    messagingSenderId: '330753230821',
    projectId: 'grocery-app-559ee',
    authDomain: 'grocery-app-559ee.firebaseapp.com',
    storageBucket: 'grocery-app-559ee.firebasestorage.app',
    measurementId: 'G-6BGEDKNSJE',
  );
}
